#!/bin/sh
module="ccontrol"
mod_path="."
device="ccontrol"
mode="666"

# remove devices
rm -f /dev/${device}?

#invode insmod
/sbin/insmod -f $mod_path/$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`
mknod /dev/${device} c $major 0
chmod $mode /dev/${device}
